#include "dds-opcua_builtin_types.idl"
@topic
struct SimpleDataType {
	boolean testBoolean;
	octet testUInt8;
	char testInt8;
	short testInt16;
	unsigned short testUInt16;
	long testInt32;
	unsigned long testUInt32;
	long long testInt64;
	unsigned long long testUInt64;
	float testFloat;
	double testDouble;
	string testString;
	OMG::DDSOPCUA::OPCUA2DDS::DateTime testDateTime;
	OMG::DDSOPCUA::OPCUA2DDS::Guid testGuid;
	OMG::DDSOPCUA::OPCUA2DDS::ByteString testByteString;
	OMG::DDSOPCUA::OPCUA2DDS::XmlElement testXmlElement;
	OMG::DDSOPCUA::OPCUA2DDS::NodeId testNodeId;
	OMG::DDSOPCUA::OPCUA2DDS::ExpandedNodeId testExpandedNodeId;
	OMG::DDSOPCUA::OPCUA2DDS::StatusCode testStatusCode;
	OMG::DDSOPCUA::OPCUA2DDS::QualifiedName testQualifiedName;
	OMG::DDSOPCUA::OPCUA2DDS::LocalizedText testLocalizedText;
	OMG::DDSOPCUA::OPCUA2DDS::ExtensionObject testExtensionObject;
	OMG::DDSOPCUA::OPCUA2DDS::BooleanArray testBooleanArray;
	OMG::DDSOPCUA::OPCUA2DDS::ByteArray testByteArray;
	OMG::DDSOPCUA::OPCUA2DDS::SByteArray testSByteArray;
	OMG::DDSOPCUA::OPCUA2DDS::Int16Array testInt16Array;
	OMG::DDSOPCUA::OPCUA2DDS::UInt16Array testUInt16Array;
	OMG::DDSOPCUA::OPCUA2DDS::Int32Array testInt32Array;
	OMG::DDSOPCUA::OPCUA2DDS::UInt32Array testUInt32Array;
	OMG::DDSOPCUA::OPCUA2DDS::Int64Array testInt64Array;
	OMG::DDSOPCUA::OPCUA2DDS::UInt64Array testUInt64Array;
	OMG::DDSOPCUA::OPCUA2DDS::FloatArray testFloatArray;
	OMG::DDSOPCUA::OPCUA2DDS::DoubleArray testDoubleArray;
	OMG::DDSOPCUA::OPCUA2DDS::StringArray testStringArray;
	OMG::DDSOPCUA::OPCUA2DDS::DateTimeArray testDateTimeArray;
	OMG::DDSOPCUA::OPCUA2DDS::GuidArray testGuidArray;
	OMG::DDSOPCUA::OPCUA2DDS::ByteStringArray testByteStringArray;
	OMG::DDSOPCUA::OPCUA2DDS::XmlElementArray testXmlElementArray;
	OMG::DDSOPCUA::OPCUA2DDS::NodeIdArray testNodeIdArray;
	OMG::DDSOPCUA::OPCUA2DDS::ExpandedNodeIdArray testExpandedNodeIdArray;
	OMG::DDSOPCUA::OPCUA2DDS::StatusCodeArray testStatusCodeArray;
	OMG::DDSOPCUA::OPCUA2DDS::QualifiedNameArray testQualifiedNameArray;
	OMG::DDSOPCUA::OPCUA2DDS::LocalizedTextArray testLocalizedTextArray;
	OMG::DDSOPCUA::OPCUA2DDS::ExtensionObjectArray testExtensionObjectArray;
	OMG::DDSOPCUA::OPCUA2DDS::BooleanMatrix testBooleanMatrix;
	OMG::DDSOPCUA::OPCUA2DDS::SByteMatrix testSByteMatrix;
	OMG::DDSOPCUA::OPCUA2DDS::ByteMatrix testByteMatrix;
	OMG::DDSOPCUA::OPCUA2DDS::Int16Matrix testInt16Matrix;
	OMG::DDSOPCUA::OPCUA2DDS::UInt16Matrix testUInt16Matrix;
	OMG::DDSOPCUA::OPCUA2DDS::Int32Matrix testInt32Matrix;
	OMG::DDSOPCUA::OPCUA2DDS::UInt32Matrix testUInt32Matrix;
	OMG::DDSOPCUA::OPCUA2DDS::Int64Matrix testInt64Matrix;
	OMG::DDSOPCUA::OPCUA2DDS::UInt64Matrix testUInt64Matrix;
	OMG::DDSOPCUA::OPCUA2DDS::FloatMatrix testFloatMatrix;
	OMG::DDSOPCUA::OPCUA2DDS::DoubleMatrix testDoubleMatrix;
	OMG::DDSOPCUA::OPCUA2DDS::StringMatrix testStringMatrix;
	OMG::DDSOPCUA::OPCUA2DDS::DateTimeMatrix testDateTimeMatrix;
	OMG::DDSOPCUA::OPCUA2DDS::GuidMatrix testGuidMatrix;
	OMG::DDSOPCUA::OPCUA2DDS::ByteStringMatrix testByteStringMatrix;
	OMG::DDSOPCUA::OPCUA2DDS::XmlElementMatrix testXmlElementMatrix;
	OMG::DDSOPCUA::OPCUA2DDS::NodeIdMatrix testNodeIdMatrix;
	OMG::DDSOPCUA::OPCUA2DDS::ExpandedNodeIdMatrix testExpandedNodeIdMatrix;
	OMG::DDSOPCUA::OPCUA2DDS::StatusCodeMatrix testStatusCodeMatrix;
	OMG::DDSOPCUA::OPCUA2DDS::QualifiedNameMatrix testQualifiedNameMatrix;
	OMG::DDSOPCUA::OPCUA2DDS::LocalizedTextMatrix testLocalizedTextMatrix;
	OMG::DDSOPCUA::OPCUA2DDS::ExtensionObjectMatrix testExtensionObjectMatrix;
};

